# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"default_pp_cfg": "01_docexp.ipynb",
         "preprocess_cell": "01_docexp.ipynb",
         "preprocess": "01_docexp.ipynb",
         "preprocess_rm_cell": "01_docexp.ipynb",
         "doc_exporter": "01_docexp.ipynb",
         "default_tpl": "01_docexp.ipynb",
         "InjectMeta": "01_docexp.ipynb",
         "ShowMeta": "01_docexp.ipynb",
         "StripAnsi": "01_docexp.ipynb",
         "InsertWarning": "01_docexp.ipynb",
         "RmEmptyCode": "01_docexp.ipynb",
         "UpdateTags": "01_docexp.ipynb",
         "HideInputLines": "01_docexp.ipynb",
         "FilterOutput": "01_docexp.ipynb",
         "CleanFlags": "01_docexp.ipynb",
         "CleanMagics": "01_docexp.ipynb",
         "BashIdentify": "01_docexp.ipynb",
         "CleanShowDoc": "01_docexp.ipynb",
         "RmHeaderDash": "01_docexp.ipynb",
         "RmExport": "01_docexp.ipynb",
         "default_pps": "01_docexp.ipynb",
         "nb2md": "01_docexp.ipynb",
         "DocExporter": "02_convert.ipynb",
         "export_docs": "02_convert.ipynb"}

modules = ["docexp.py",
           "convert.py"]

doc_url = "https://nbdev2.github.io/"

git_url = "https://github.com/fastai/nbdev2/tree/master/"

def custom_doc_links(name): return None
