# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_quarto.ipynb.

# %% ../nbs/03_quarto.ipynb 1
from __future__ import annotations
import json

from nbprocess.read import *
from nbprocess.sync import *
from nbprocess.process import *
from nbprocess.processors import *
from fastcore.imports import *
from fastcore.all import Path,parallel,call_parse,bool_arg,globtastic

# %% auto 0
__all__ = ['default_procs', 'default_preprocs', 'filter_quarto']

# %% ../nbs/03_quarto.ipynb 4
def default_procs():
    "Default Preprocessors for export"
    return [strip_ansi, meta_, hide_line, filter_stream_, clean_magics,
            bash_identify, rm_header_dash, rm_export, clean_show_doc, remove_]

# %% ../nbs/03_quarto.ipynb 5
def default_preprocs():
    "Default Preprocessors for export"
    return [insert_warning]

# %% ../nbs/03_quarto.ipynb 6
def filter_quarto(s=None):
    printit = False
    if not s:
        s = sys.stdin.read()
        printit = True
    nb = dict2nb(json.loads(s))
    nbp = NBProcessor(nb=nb, procs=default_procs(), preprocs=default_preprocs())
    nbp.process()
    res = nb2str(nb)
    if printit: print(res)
    else: return res
